line-length = 88
unsafe-fixes = false
target-version = "py39"
extend = "./pyproject.toml"

[lint]
extend-select = [
    "D417", # undocumented-param
    "I",    # isort
    "UP",   # pyupgrade
    "ISC",  # flake8-implicit-str-concat
    "G",    # flake8-logging-format
    "LOG",  # flake8-logging
    "PT",   # flake8-pytest-style
    "E",    # pycodestyle
    "W",    # pycodestyle
    "PGH",  # pygrep-hooks
    "B",    # flake8-bugbear
    "TRY",  # tryceratops
    "S101", # assert
]
ignore = []
fixable = ["I", "UP", "ISC", "G", "LOG", "PT", "E", "W", "PGH", "B"]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint.pylint]
max-args = 10

[lint.isort]
known-local-folder = ["bayes_opt"]
required-imports = ["from __future__ import annotations"]
# ruff format
force-single-line = false
force-wrap-aliases = false
split-on-trailing-comma = false

[lint.pydocstyle]
convention = "numpy"
