line-length = 110
unsafe-fixes = false
target-version = "py39"
extend = "./pyproject.toml"
exclude = [
    # related: PR#447
    "bayes_opt/acquisition.py",
    "bayes_opt/bayesian_optimization.py",
    "bayes_opt/util.py",
    "tests/test_acquisition.py",
    "tests/test_bayesian_optimization.py",
    "tests/test_constraint.py",
    "tests/test_util.py",
    # docs
    "docsrc/**/*",
    # examples
    "examples/**/*",
]

[lint]
extend-select = [
    # "D",      # pydocstyle # TODO
    "D417",   # undocumented-param
    "I",      # isort
    "UP",     # pyupgrade
    "G",      # flake8-logging-format
    "LOG",    # flake8-logging
    "PT",     # flake8-pytest-style
    "E",      # pycodestyle
    "W",      # pycodestyle
    "PGH",    # pygrep-hooks
    "B",      # flake8-bugbear
    "SIM",    # flake8-simplify
    "S",      # flake8-bandit
    "DTZ",    # flake8-datetimez
    "EM",     # flake8-errmsg 
    "TRY002", # raise-vanilla-class
]
ignore = [
    "PT011", # TODO
]
fixable = ["I", "UP", "ISC", "G", "LOG", "PT", "E", "W", "PGH", "B", "SIM", "S"]

[lint.per-file-ignores]
"tests/test_*.py" = ["S101"]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint.pylint]
max-args = 10

[lint.isort]
known-local-folder = ["bayes_opt"]
required-imports = ["from __future__ import annotations"]
# ruff format
force-single-line = false
force-wrap-aliases = false
split-on-trailing-comma = false

[lint.pydocstyle]
convention = "numpy"
