# This workflow will install Python dependencies and run tests in multiple versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Python ${{ matrix.python-version }} - ${{ matrix.numpy-constraints }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
        numpy-constraints: ["numpy>=1.25,<2 scipy<1.18", "numpy>=2"] # scipy>=1.18 is not supported on numpy<2
        exclude:
          - python-version: "3.13" # numpy<2 is not supported on 3.13+
            numpy-constraints: "numpy>=1.25,<2 scipy<1.18"
          - python-version: "3.14"
            numpy-constraints: "numpy>=1.25,<2 scipy<1.18"
          - python-version: "3.14t"
            numpy-constraints: "numpy>=1.25,<2 scipy<1.18"

    steps:
    - uses: actions/checkout@v3
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        uv sync --extra dev
        uv pip install "{{ matrix.numpy-constraints }}"
    - name: Run pytest
      run: uv run --no-sync pytest --cov-report xml --cov=bayes_opt/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
